language: java
script: mvn verify deploy --settings maven_deploy_settings.xml
jdk:
- oraclejdk7
- openjdk7
notifications:
  email:
    recipients:
    - yammer-sonatype@microsoft.com
env:
  global:
  - secure: a3H5vWCqW6GkF7YqxDzqYW8pCrqrJPODR3cf0O1Cf9Zdxd6bcTrq/S42k1XBV1QdLJGrm2dOpco1h8Qo970Pq+XHhnH1Qb6Cp+bk7xuL9VcM5YVkUlMehwzTwi0Z8R4Yc+Iphq26OSn+16XNdVdi9IhmXg4qXY/cExb8gGTTIiM=
  - secure: VCzRUlNbHKRBH4q0E6mDbVrXxm4QSbUk5Knb/XruanB1Ti4Z9IajKLKJAR2AGRGXBa1kL+jdnUlQwkP6lO1mOeDxp074lrMhNJQ8qeJfNzrlMFc0bguOMsx+hHiwD7HyPBblAO+3jDC37P5IFOExDR9ModTIHybWIVdJkd4/5DY=
